In [111]:
import torch
print(torch.__version__)

2.6.0


In [112]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
    
else:
    print("No GPU available")

No GPU available


In [113]:
a = torch.empty(2, 3)  #using empty    


In [114]:
type(a) # type of

torch.Tensor

In [115]:
#using zero 
b = torch.zeros(5,3)


In [116]:
torch.ones(2,3) #using ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [117]:
torch.rand(2,3)  #using rand

tensor([[0.8752, 0.2810, 0.3321],
        [0.3408, 0.5142, 0.4260]])

In [118]:
#using manual seed
torch.manual_seed(29)
torch.rand(2,3)

tensor([[0.1226, 0.9355, 0.9359],
        [0.7038, 0.7536, 0.3418]])

In [119]:
torch.manual_seed(29) 
torch.rand(2,3)

tensor([[0.1226, 0.9355, 0.9359],
        [0.7038, 0.7536, 0.3418]])

In [120]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]]) 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [121]:
x = torch.tensor([[1,2,3],[4,5,6]]) 
x.shape

torch.Size([2, 3])

In [122]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [123]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [124]:
torch.ones_like(x) 

tensor([[1, 1, 1],
        [1, 1, 1]])

In [125]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [126]:
x.dtype

torch.int64

In [127]:
random_tensor = x.float()
torch.rand_like(random_tensor)

tensor([[0.3887, 0.5124, 0.8961],
        [0.3233, 0.8280, 0.7258]])

In [128]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64) #creating tensors with different data types
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [129]:
x.to(int)  #converting float to int after creating the tensors 

tensor([[1, 2, 3],
        [4, 5, 6]])

Mathematical Operations

1.scalar operations

In [130]:
x = torch.rand(2,2)
x

tensor([[0.0188, 0.7800],
        [0.3197, 0.9042]])

In [131]:
#addition
x + 2

tensor([[2.0188, 2.7800],
        [2.3197, 2.9042]])

In [132]:
#subtraction
x-2

tensor([[-1.9812, -1.2200],
        [-1.6803, -1.0958]])

In [133]:
#multiplication
x*3

tensor([[0.0563, 2.3401],
        [0.9591, 2.7125]])

In [134]:
#division
x/2

tensor([[0.0094, 0.3900],
        [0.1599, 0.4521]])

In [135]:
#int division
(x*100)//3
 

tensor([[ 0., 26.],
        [10., 30.]])

In [136]:
#mod
((x*100)//3)%2

tensor([[0., 0.],
        [0., 0.]])

In [139]:
#power
x**2

tensor([[3.5189e-04, 6.0843e-01],
        [1.0221e-01, 8.1753e-01]])

Element Wise Operations


In [142]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2227, 0.7766, 0.2755],
        [0.4387, 0.1433, 0.2366]])
tensor([[0.0163, 0.5165, 0.4442],
        [0.6900, 0.5831, 0.7750]])


In [143]:
a + b

tensor([[0.2390, 1.2931, 0.7196],
        [1.1287, 0.7264, 1.0117]])

In [144]:
a - b

tensor([[ 0.2065,  0.2601, -0.1687],
        [-0.2513, -0.4398, -0.5384]])

In [145]:
a * b

tensor([[0.0036, 0.4011, 0.1224],
        [0.3027, 0.0835, 0.1834]])

In [146]:
a / b

tensor([[13.7013,  1.5037,  0.6201],
        [ 0.6358,  0.2457,  0.3053]])

In [148]:
a ** b #power

tensor([[0.9759, 0.8776, 0.5640],
        [0.5664, 0.3221, 0.3272]])

In [150]:
a % b #mod

tensor([[0.0114, 0.2601, 0.2755],
        [0.4387, 0.1433, 0.2366]])

In [152]:
a // b #floor division

tensor([[13.,  1.,  0.],
        [ 0.,  0.,  0.]])

In [159]:
#absolute value - abs
c = torch.tensor([1,-2,3,-4])
c.abs()   #objected oriented style
torch.abs(x) #functional programming style

tensor([[0.0188, 0.7800],
        [0.3197, 0.9042]])

In [164]:
#negative
c.neg() # or #
torch.neg(c) #both are same

tensor([-1,  2, -3,  4])

In [167]:
d = torch.tensor([1.9,2.9,3.7,4.2])
print(d)

tensor([1.9000, 2.9000, 3.7000, 4.2000])


In [176]:
torch.round(d)
d.round()    #same bro rounding values

tensor([2., 3., 4., 4.])

In [178]:
#ceil
d.ceil() # takes the value towards upper value (rounds it to upper limit)

tensor([2., 3., 4., 5.])

In [180]:
d.floor() # takes the value towards its lower value ( rounds the value to it lower limit)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
d.clamp(2,3) # minimum and maximum use gpt to understand this its about rounding values to nearest value to either min or max

tensor([2.0000, 2.9000, 3.0000, 3.0000])

Reduction Operations

In [189]:
e = torch.randint(size= (2,3) , low = 0 , high = 10 )
print(e)

tensor([[9, 5, 8],
        [2, 7, 1]])


In [192]:
e.sum() # sums all the values in the matric

tensor(32)

In [195]:
#sum along the colums
e.sum(dim=0) #taking zero dimenstionality which is scalar

tensor([11, 12,  9])

In [198]:
#sum along the rows
e.sum(dim=1)  # use chatgpt to understand more about this in the future

tensor([22, 10])

In [203]:
#mean
e.mean(dtype=float)

tensor(5.3333, dtype=torch.float64)