In [15]:
import torch
import numpy as np

In [16]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [17]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [18]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
tensor_a.add_(tensor_b) #re-assignment to the orginal var without creating new var

tensor([16, 20, 24, 28])

In [21]:
tensor_a

tensor([ 6,  8, 10, 12])